# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

variables:

steps:
- task: GoTool@0
  inputs:
    version: '1.13'
- task: NodeTool@0 
  inputs:
    versionSpec: '12.x'

- script: |
    npm install
    npm run build
  workingDirectory: $(system.defaultWorkingDirectory)/fe-gui
  displayName: 'Exter-FE: install dependencies and build'

- task: Go@0
  inputs:
    command: 'build'
    arguments: '-o main'
    workingDirectory: '$(System.DefaultWorkingDirectory)/be-api'
  displayName: 'Exter-BE: build'

- task: Go@0
  inputs:
    command: 'test'
    arguments: '-v -cover'
    workingDirectory: '$(System.DefaultWorkingDirectory)/be-api'
  displayName: 'Exter-BE: test'

- task: Docker@2
  inputs:
    command: build
    repository: 
    tags: exter
    workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Exter: build all-in-one docker image'
