# Azure pipeline to build & deploy Exter

trigger:
  batch: true
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  appName: exter
  appVersion: '0.1.0'
  goVersion: '1.13'
  goBuiltAppName: 'main'
  nodejsVersion: '12.x'
  dockerVersion: '19.03.9'
  branchMasterChanged: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/master') }}

stages:
  - stage: build
    displayName: Build project
    jobs:
      - job: build
        displayName: Build project
        steps:
        - task: GoTool@0
          displayName: Prepare Go env
          inputs:
            version: '$(goVersion)'
        - task: NodeTool@0
          displayName: Prepare NodeJs env
          inputs:
            versionSpec: '$(nodejsVersion)'
        - task: DockerInstaller@0
          displayName: Prepare Docker CLI
          inputs:
            dockerVersion: '$(dockerVersion)'
            releaseType: 'stable'
        - task: Npm@1
          displayName: 'FE: npm install'
          inputs:
            command: install
            workingDir: '$(System.DefaultWorkingDirectory)/fe-gui'
        - task: Npm@1
          displayName: 'FE: npm run build'
          inputs:
            command: custom
            customCommand: 'run build'
            workingDir: '$(System.DefaultWorkingDirectory)/fe-gui'
        - task: Go@0
          displayName: 'BE: go build'
          inputs:
            command: build
            arguments: '-o $(goBuiltAppName) -tags netgo -a'
            workingDir: '$(System.DefaultWorkingDirectory)/be-api'
        - task: Go@0
          displayName: 'BE: go test'
          inputs:
            command: test
            arguments: '-v --cover'
            workingDir: '$(System.DefaultWorkingDirectory)/be-api'
