# Azure pipeline to build & deploy Exter

trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  appName: exter
  appVersion: '0.1.0'
  goVersion: '1.13'
  nodejsVersion: '12.x'
  dockerVersion: '19'
  branchMasterChanged: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/master') }}

stages:
  - stage: build
    displayName: Build project
    jobs:
      - job: build
        displayName: Build project
        steps:
        - task: GoTool@0
          displayName: Prepare Go env
          inputs:
            version: '$(goVersion)'
        - task: NodeTool@0
          displayName: Prepare NodeJs env
          inputs:
            versionSpec: '$(nodejsVersion)'
        - task: DockerInstaller@0
          displayName: Prepare Docker CLI
          inputs:
            dockerVersion: '$(dockerVersion)'
            releaseType: 'stable'
