# Azure pipeline to build & deploy Exter

trigger:
  batch: true
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  goVersion: '1.13'
  goBuiltAppName: 'main'
  nodejsVersion: '13.x'
  dockerVersion: '19.03.9'
  herokuRegistry: 'registry.heroku.com'
  herokuApp: 'demo-exter'
  branchMasterChanged: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/master') }}

stages:
  - stage: build
    displayName: Build project
    jobs:
      - job: build
        displayName: Build project
        steps:
        - task: GoTool@0
          displayName: Prepare Go env
          inputs:
            version: '$(goVersion)'
        - task: NodeTool@0
          displayName: Prepare NodeJs env
          inputs:
            versionSpec: '$(nodejsVersion)'
        - task: DockerInstaller@0
          displayName: Prepare Docker CLI
          inputs:
            dockerVersion: '$(dockerVersion)'
            releaseType: 'stable'
        - task: Npm@1
          displayName: 'FE: npm install'
          inputs:
            command: install
            workingDir: '$(System.DefaultWorkingDirectory)/fe-gui'
        - task: Npm@1
          displayName: 'FE: npm run build'
          inputs:
            command: custom
            customCommand: 'run build'
            workingDir: '$(System.DefaultWorkingDirectory)/fe-gui'
        - script: cd $(System.DefaultWorkingDirectory)/be-api && go build -o $(goBuiltAppName) -tags netgo -a
          displayName: 'BE: go build'
        - script: cd $(System.DefaultWorkingDirectory)/be-api && go test -v --cover
          displayName: 'BE: go test'

  - stage: deploy_heroku
    displayName: Build image and deploy to Heroku
    dependsOn: build
    condition: eq(variables['branchMasterChanged'], false)
    variables:
      - group: Release
    jobs:
      - job: build
        displayName: Build image
        steps:
        - task: DockerInstaller@0
          displayName: Prepare Docker CLI
          inputs:
            dockerVersion: '$(dockerVersion)'
            releaseType: 'stable'
        - script: |
            APP_NAME=`jq -r '.name' $(System.DefaultWorkingDirectory)/appinfo.json`
            echo '##vso[task.setvariable variable=APP_NAME]'$APP_NAME
            APP_SHORTNAME=`jq -r '.shortname' $(System.DefaultWorkingDirectory)/appinfo.json`
            echo '##vso[task.setvariable variable=APP_SHORTNAME]'$APP_SHORTNAME
            APP_INITIAL=`jq -r '.initial' $(System.DefaultWorkingDirectory)/appinfo.json`
            echo '##vso[task.setvariable variable=APP_INITIAL]'$APP_INITIAL
            APP_VERSION=`jq -r '.version' $(System.DefaultWorkingDirectory)/appinfo.json`
            echo '##vso[task.setvariable variable=APP_VERSION]'$APP_VERSION
            APP_DESC=`jq -r '.description' $(System.DefaultWorkingDirectory)/appinfo.json`
            echo '##vso[task.setvariable variable=APP_DESC]'$APP_DESC
            sed -i 's/{?HTTP_LISTEN_PORT}/{?PORT}/g' $(System.DefaultWorkingDirectory)/be-api/config/api.conf
            sed -i 's/{?DB_PGSQL_URL}/{?DATABASE_URL}/g' $(System.DefaultWorkingDirectory)/be-api/config/conf.d/api_gvabe.conf
            rm -f $(System.DefaultWorkingDirectory)/fe-gui/.env
          displayName: Init application info
        - task: Docker@2
          displayName: Build Docker image
          inputs:
            command: build
            buildContext: '$(System.DefaultWorkingDirectory)'
            repository: '$(APP_SHORTNAME)'
            tags: latest
        - script: |
            echo Logging in to $(herokuRegistry)...
            export HEROKU_API_KEY=$(HerokuToken)
            echo $(HerokuToken) | docker login -u _ --password-stdin $(herokuRegistry)
            docker tag $(APP_SHORTNAME) $(herokuRegistry)/$(herokuApp)/web
            docker images
            echo Pushing image...
            docker push $(herokuRegistry)/$(herokuApp)/web
            echo Releasing image...
            heroku container:release web -a $(herokuApp)
            echo Logging out...
            docker logout $(herokuRegistry)
            unset HEROKU_API_KEY
          displayName: Push and Deploy to Heroku
