apiVersion: v1
kind: Service
metadata:
  name: {{ include "exter.name" . }}
  labels:
    {{- include "exter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "exter.selectorLabels" . | nindent 4 }}
